name: cc_workout_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  supabase_flutter: ^2.3.4
  intl: ^0.20.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  go_router: 17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  build_test: ^3.5.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
